version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: nomad-vector-logger.bin
    id: nomad-vector-logger
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: .

archives:
  - formats:
      - tar.gz
    files:
      - README.md
      - LICENSE
      - config.sample.toml

dockers:
  - id: docker-amd64
    goos: linux
    goarch: amd64
    ids:
      - nomad-vector-logger
    image_templates:
      - "ghcr.io/mr-karan/nomad-vector-logger:{{ .Tag }}-amd64"
      - "ghcr.io/mr-karan/nomad-vector-logger:latest-amd64"
    skip_push: false
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - config.sample.toml

  - id: docker-arm64
    goos: linux
    goarch: arm64
    ids:
      - nomad-vector-logger
    image_templates:
      - "ghcr.io/mr-karan/nomad-vector-logger:{{ .Tag }}-arm64"
      - "ghcr.io/mr-karan/nomad-vector-logger:latest-arm64"
    skip_push: false
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - config.sample.toml

docker_manifests:
  - name_template: ghcr.io/mr-karan/nomad-vector-logger:{{ .Tag }}
    image_templates:
      - ghcr.io/mr-karan/nomad-vector-logger:{{ .Tag }}-amd64
      - ghcr.io/mr-karan/nomad-vector-logger:{{ .Tag }}-arm64
  - name_template: ghcr.io/mr-karan/nomad-vector-logger:latest
    image_templates:
      - ghcr.io/mr-karan/nomad-vector-logger:latest-amd64
      - ghcr.io/mr-karan/nomad-vector-logger:latest-arm64
